name: UpdateSinaTopHot 

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  UpdateGist:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Action Execute
      env:
        GIST_ID: 7914cf6796514691fd5e99d213e44f78
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TZ: Asia/Shanghai
      run: |
        python SinaTopHot.py